### ISSUE TITLE
sshfs is very slow compared to scp

### ISSUE THREAD

**Issue by shuokay** [libfuse/sshfs#63] opened 2017-06-23 03:15 UTC
I am using Macbook, and mount a remote cenos machine.
1. when  `ls` in terminal, all files displayed immediately but the promote show up after several seconds.
2. When play a video about 100M, the play is not smooth, but when `scp` this video to local machine it takes less than 5 seconds.

**Comment by Jakuje** [comment] 2017-06-23 18:39
And where is the comparison to the `scp`?

**Comment by shuokay** [comment] 2017-06-24 02:05
@Jakuje updated the comment

**Comment by Nikratio** [comment] 2017-06-24 03:23
Looks like a duplicate of #11 - please feel free to re-open if you have data that indicates that this has a different cause.

**Closed by Nikratio** 2017-06-24 03:23 UTC
Labels: duplicate
