### ISSUE TITLE
sshfs 2.x segfaults if mount directory is not supplied

### ISSUE THREAD

**Issue by coderforlife** [libfuse/sshfs#75] opened 2017-07-31 17:45 UTC
I am building the sshfs 2.x branch and it segfaults if you forget the mount path but include the host information. With the sshfs 2.9 on brew it instead reports "Bad address". Unsure if this is fixed in master. In any case it should report a better message than "Bad address" or segfaulting.

On a somewhat related note, since this is on a Mac I assumed I needed the 2.x branch instead of master since master says it requires libfuse 3.1.0 and the OSXFUSE only claims to support v2.9.7.

**Comment by Nikratio** [comment] 2017-08-03 16:19
Thanks for the report! I can reproduce and will look into it.

```
$ sshfs --version
SSHFS version 2.8
FUSE library version: 2.9.7
fusermount version: 2.9.7
using FUSE kernel interface version 7.19

$ ./sshfs foo
missing host
see `./sshfs -h' for usage

$ ./sshfs foo:
Bad address
```

**Comment by Nikratio** [comment] 2017-08-03 16:22
This is fixed in SSHFS 3.x. Since this is not a high-impact bug I am unlikely to fix it in SSHFS 2.x. But I'm happy to review a patch if someone else wants to work on it.

**Closed** 2019-04-14 10:53 UTC
Labels: bug
