### ISSUE TITLE
sshfs freezes on connect if dir to be mounted is specified as first in PATH variable.

### ISSUE THREAD

**Issue by Perza-e** [libfuse/sshfs#196] opened 2019-11-22 10:52 UTC
So sshfs freezes whole user and will not react to CTRL+C signal. Only initiating kill -9 <sshfs_pid> as root user clears the freeze situation. It also causes the mount point to go stale:
#ls -l
d?????????  ? ?    ?            ?            ? some_dir

**Cause:** 
It took really long time to find the cause of this problem.

Local directory to be mounted: /home/user/some_dir

So let's say that we have e.g. this kind of path normally:
/home/user/bin:/home/user/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

If I add the directory to be mounted in the **beginning** of the PATH, **sshfs freezes on connect**.
**/home/user/some_dir**:/home/user/bin:/home/user/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

If I add the directory to be mounted in the **end** of the PATH, **sshfs works just fine**:
/home/user/bin:/home/user/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:**/home/user/some_dir**

Command used:
#cd ~
run as normal user:
#sshfs -o nonempty user@mgmt:/home/user/some_dir some_dir

System:
Ubuntu 16.04.6 LTS
sshfs 2.5-1ubuntu1
fuse 2.9.4-1ubuntu3.1

Debug:
#sshfs -o debug,sshfs_debug,loglevel=debug,nonempty user@mgmt:/home/user/some_dir some_dir
SSHFS version 2.5
FUSE library version: 2.9.4
nullpath_ok: 0
nopath: 0
utime_omit_ok: 0
executing <ssh> <-x> <-a> <-oClearAllForwardings=yes> <-ologlevel=debug> <-2> some_user@mgmt <-s> <sftp>
HANG....

Fix suggestion:
- Check if path in $PATH really exists before trying to access it OR check if local directory to be mounted is in PATH before trying to connect to the remote with ssh
- Give a proper error message rather than just freezing.

**Comment by Nikratio** [comment] 2019-11-23 12:18
This is because SSHFS first registers the mountpoint, and then attempts to call the SSH binary. The binary will then be searched in PATH, which means means the mountpoint is accessed, but responding to this request requires the SSH connection to be up.

The proper fix would be to first call SSH, and then do the mount. Patches welcome :-).

**Comment by mathieu-aubin** [comment] 2020-01-01 12:23
@Perza-e It seems that by adding `-o ssh_command=$(which ssh)` the issue is no longer a problem

**Comment by Nikratio** [comment] 2020-03-13 16:39
Thank you for the report! The problem is most likely that we first open the mountpoint and then fork SSH. So if the shell or ssh tries to access the mountpoint, everything hangs.

Do you think you could work on this (or do you know someone who could)?

SSHFS is a fully volunteer driven project. This means that new features and bugfixes are implemented only when someone has a personal interest in them and therefore also does the necessary work. So if someone (that probably means you) is interested in working on this, then I'd be happy to give guidance and review patches. If not, I will close this issue in a few days (since the purpose of the issue tracker is to coordinate ongoing and planned work, rather than enumerate all the work that could possibly be done).

**Comment by Nikratio** [comment] 2020-11-09 09:49
I'm closing this issue for now. Please note that this isn't meant to imply that you haven't found a valid bug or potential improvement - you most likely have and I'm grateful that you took the time to report it.

Unfortunately, this project does not currently have any active, regular contributors or developers. The current maintainer continues to apply pull requests and tries to make regular releases, but unfortunately has no capacity to do any development beyond addressing high-impact issues. Any other reports are therefore likely to languish unless they come together with a high-quality pull request.

This report unfortunately does not fall into either category, so with the current state of affairs it's unlikely that anyone is going to be able to do anything but this anytime soon, and I prefer to use the issue tracker as a tool to manage ongoing work (as opposed to a database of known/potential issues).

**Closed by Nikratio** 2020-11-09 09:49 UTC
