### ISSUE TITLE
utimensat(NULL) not handled correctly

### ISSUE THREAD

**Issue by Nelyah** [libfuse/sshfs#112] opened 2018-01-07 13:12 UTC
I am not quite sure if this is a bug or if this is intended. The short version is, files created through the `touch` command have a creation date from 1970.

This is a cross-post from [Unix - StackExchange](https://unix.stackexchange.com/questions/415072/new-files-created-through-sshfs-date-from-1970) as I wasn't able to get an answer there.
I wish to mount a remote Linux directory to my local laptop using sshfs. I do this by using autofs. In `/etc/autofs/`, I therefore have in the `auto.ssh` file (I used the [Arch wiki][1] to guide me for the options I should use):

    cluster -fstype=fuse,rw,allow_other,IdentityFile=/home/mia/.ssh/id_rsa :sshfs\#mia@host\:

In the `auto.master` file I added the line:

    /home/mia/remote        /etc/autofs/auto.ssh    uid=1000,gid=1000,--ghost,--timeout=60
The folder is successfully mounted and its date is accurate:

     drwxr-xr-x  4 root  root     0 Jan  5 19:51 remote

However, if I create a new file inside the remote folder, the file's date is epoch (01-01-1970).

    $ cd remote/cluster
    $ touch test
    $ cp test test2
    $ ls -l test*
    -rw-r--r-- 1 mia mia    0 Jan  1  1970 test
    -rw-r--r-- 1 mia mia    0 Jan  7 14:07 test2

I have searched the man pages of mount, mount.fuse, sshfs, autofs but to no avail. I haven't been either able to determine if this was a bug or a feature. 

Both computers are up-to-date Linux Manjaro distribution.

  [1]: https://wiki.archlinux.org/index.php/SSHFS#Secure_user_access

**Comment by Blackclaws** [comment] 2018-02-01 14:23
Can reproduce. Also file editing does not update timestamps for me. Copying works as described.

**Comment by quite** [comment] 2018-02-22 11:51
I *cannot* reproduce this with fuse 2.9.4-1ubuntu3.1, sshfs 2.5-1ubuntu1 on Ubuntu 16.04 Xenial. If I install fuse3 from bkryza/fuse3 PPA, and compile sshfs from current git master, I do get the 1970-01-01 timestamp when issuing `touch`. Same result on a fresh Arch Linux, with fuse3 3.2.1, sshfs 3.3.1.

On a lower level, it is calls to `utimensat(2)` (which touch uses) and `utimes(2)` with the time argument as NULL (which should result in current time, and is, according to `strace`, what `touch` does) which result in 1970-01-01. Calling `utimensat(2)` with non-NULL does indeed get the timestamp through.

**Comment by Nikratio** [comment] 2018-02-25 13:03
Thanks for the reports! Shouldn't be too hard to fix.

**Comment by quite** [comment] 2018-02-25 14:11
Can this be solved here in sshfs, or is there a need to poke in fuse? I just had a very quick peek into the code, and perhaps it's just a matter of teaching `sshfs_open_common` to get `utimens` down through to sftp.

**Comment by Nikratio** [comment] 2018-02-26 14:49
Most likely this can be fixed in SSHFS.

**Comment by quite** [comment] 2018-03-29 16:19
Hm, now that I'm in European Summer Time, CEST. The files created with `touch` as above get the timestamp`1970-01-01 01:00:00.000000000 +0100`. A file actually created at `00:00:00` that day looks like `2106-02-07 06:28:16.000000000 +0100` :-O

**Comment by quite** [comment] 2018-06-16 06:06
I made a stab at this ^^^

**Comment by Nikratio** [comment] 2018-06-18 18:13
Fixed in commit f0452119e0

**Closed by Nikratio** 2018-06-18 18:13 UTC
Labels: bug
