### ISSUE TITLE
UseProxyIf in ssh_config results in remote host disconnected

### ISSUE THREAD

**Issue by mvanderkolff** [libfuse/sshfs#14] opened 2016-03-30 00:05 UTC
When using UseProxyIf on 

MacOS X 10.11.4 with 

SSHFS version 2.5 (OSXFUSE SSHFS 2.5.0)
OSXFUSE library version: FUSE 2.7.3 / OSXFUSE 2.8.0

if UseProxyIf is present in the applicable config, independent of whether or not the command succeeds, we get:
ssh_check_need_proxy: waitpid: No child processes
remote host has disconnected

Steps to reproduce:
1. Put "UseProxyIf /bin/false" in a config
2. Use sshfs to that host.

**Comment by Nikratio** [comment] 2016-06-05 18:24
What do you get when you try to call ssh directly? I get:

```
$ ./sshfs localhost: ~/tmp/mnt
read: Connection reset by peer

$ ssh localhost
/home/nikratio/.ssh/config: line 3: Bad configuration option: useproxyif
/home/nikratio/.ssh/config: terminating, 1 bad configuration options
```

Maybe you have the same problem?

**Comment by studgeek** [comment] 2016-08-08 23:41
I'm able to reproduce this also.


 With the following .ssh/config file I get the sshfs error results listed below it:
```
Match host *.corp.company.com
  ProxyCommand corp-ssh-helper %h %p
  UseProxyIf curl -sI "https://path.corp.company.com/apath" | grep -q "^Location:.*/no"
```

```
debug1: Executing need proxy command: exec curl -sI "https://path.corp.company.com/apath" | grep -q "^Location:.*/no"
debug1: permanently_drop_suid: 199179
ssh_check_need_proxy: waitpid: No child processes
remote host has disconnected
```

Switching the UseProxyIf to something simpler also gives an error:
```
Match host *.corp.company.com
  ProxyCommand corp-ssh-helper %h %p
  UseProxyIf /bin/false
```

```
debug1: Executing need proxy command: exec /bin/false
debug1: permanently_drop_suid: 199179
/bin/bash: /bin/false: No such file or directory
/bin/bash: line 0: exec: /bin/false: cannot execute: No such file or directory
ssh_check_need_proxy: waitpid: No child processes
remote host has disconnected
```

If I delete the UseProxyIf line so I just have the following then sshfs succeeds:
```
Match host *.corp.company.com
  ProxyCommand corp-ssh-helper %h %p
```

ssh works fine with all three configs.

**Comment by studgeek** [comment] 2016-08-09 00:09
Using exec on the Match line causes the same issue for sshfs. Config and error below: 

```
Match host *.corp.company.com exec "curl -sI https://debug.corp.company.com/oncorp | grep -q '^Location:.*/no'"
```

```
debug1: Executing command: 'curl -sI https://uberproxy-debug.corp.company.com/oncorp | grep -q '^Location:.*/no''
debug1: permanently_drop_suid: 199179
execute_in_shell: waitpid: No child processes
remote host has disconnected
```

**Comment by Nikratio** [comment] 2017-06-03 17:03
Thanks for the reports! I will see what I can do, this seems rather odd.

**Comment by Nikratio** [comment] 2017-06-05 16:23
I have trouble reproducing this, because my ssh doesn't know anything about an `UseProxyIf` option. Neither does http://man.openbsd.org/ssh_config. Which SSH are you using?

**Comment by Nikratio** [comment] 2017-09-19 21:22
I'm closing this bug report for now. Please note that this isn't meant to imply that you haven't found a bug - you most likely have and I'm grateful that you took the time to report it. However, without additional information it is unlikely that anyone is going to be able to do anything but this, and I prefer to use the issue tracker as a tool to manage ongoing work (as opposed to a database of known/potential issues). 

Please feel free to re-open this if you can provide the requested information!

**Closed by Nikratio** 2017-09-19 21:22 UTC
Labels: bug, needs-info
