### ISSUE TITLE
Permission denied when copying within same SSHFS mount.

### ISSUE THREAD

**Issue by markcaudill** [libfuse/sshfs#110] opened 2017-12-20 16:24 UTC
I'm able to copy from local to SSHFS and from one SSHFS to a different SSHFS mount, but I can't copy a file within the SSHFS mount (I've tried this on multiple SSHFS mounts). Below is the debug output for a local -> SSHFS `cp` and a same-mount SSHFS `cp` (which fails) for comparison. They both have the `CREATE` operation but one fails and the other succeeds and I can't tell why. Any help would be greatly appreciated.

### Move file from local filesystem to an SSHFS filesystem
```
# cp /tmp/tmp .
```

#### Debug Output
```
unique: 12, opcode: GETATTR (3), nodeid: 1, insize: 56
getattr /
   unique: 12, success, outsize: 120
unique: 13, opcode: LOOKUP (1), nodeid: 1, insize: 44
LOOKUP /tmp
getattr /tmp
   unique: 13, error: -2 (No such file or directory), outsize: 16
unique: 14, opcode: LOOKUP (1), nodeid: 1, insize: 44
LOOKUP /tmp
getattr /tmp
   unique: 14, error: -2 (No such file or directory), outsize: 16
unique: 15, opcode: CREATE (35), nodeid: 1, insize: 60
create flags: 0x80c1 /tmp 0100644 umask=0022
   create[140105322860400] flags: 0x80c1 /tmp
fgetattr[140105322860400] /tmp
   NODEID: 6
   unique: 15, success, outsize: 160
unique: 16, opcode: FLUSH (25), nodeid: 6, insize: 64
flush[140105322860400]
   unique: 16, success, outsize: 16
unique: 17, opcode: RELEASE (18), nodeid: 6, insize: 64
release[140105322860400] flags: 0x8001
   unique: 17, success, outsize: 16
```

### Copy file within same SSH filesystem
```
# cp tmp tmp2
cp: cannot create regular file `tmp2': Permission denied
```

#### Debug Output
```
unique: 19, opcode: GETATTR (3), nodeid: 1, insize: 56
getattr /
   unique: 19, success, outsize: 120
unique: 20, opcode: LOOKUP (1), nodeid: 1, insize: 45
LOOKUP /tmp2
getattr /tmp2
   unique: 20, error: -2 (No such file or directory), outsize: 16
unique: 21, opcode: LOOKUP (1), nodeid: 1, insize: 44
LOOKUP /tmp
getattr /tmp
   NODEID: 6
   unique: 21, success, outsize: 144
unique: 22, opcode: LOOKUP (1), nodeid: 1, insize: 45
LOOKUP /tmp2
getattr /tmp2
   unique: 22, error: -2 (No such file or directory), outsize: 16
unique: 23, opcode: LOOKUP (1), nodeid: 1, insize: 44
LOOKUP /tmp
getattr /tmp
   NODEID: 6
   unique: 23, success, outsize: 144
unique: 24, opcode: OPEN (14), nodeid: 6, insize: 48
open flags: 0x8000 /tmp
   open[140105188644672] flags: 0x8000 /tmp
   unique: 24, success, outsize: 32
unique: 25, opcode: LOOKUP (1), nodeid: 1, insize: 45
LOOKUP /tmp2
getattr /tmp2
   unique: 25, error: -2 (No such file or directory), outsize: 16
unique: 26, opcode: CREATE (35), nodeid: 1, insize: 61
create flags: 0x80c1 /tmp2 0100755 umask=0022
   unique: 26, error: -13 (Permission denied), outsize: 16
unique: 27, opcode: FLUSH (25), nodeid: 6, insize: 64
flush[140105188644672]
   unique: 27, success, outsize: 16
unique: 28, opcode: RELEASE (18), nodeid: 6, insize: 64
release[140105188644672] flags: 0x8000
   unique: 28, success, outsize: 16
```

### Options (from fstab)
```
fuse.sshfs debug,delay_connect,_netdev,user,idmap=user,transform_symlinks,identityfile=/root/.ssh/id_rsa,allow_other,default_permissions,uid=805,gid=805,reconnect,umask=0002,workaround=all
```

**Comment by Nikratio** [comment] 2018-06-22 09:22
Thanks for the report, and sorry for not responding for so long! This might be hard to debug, because for most people (including me) this obviously works just fine.

Can you try to reproduce this with exactly the same file? Note that the create flags and filenames are different for the two CREATE calls.

Also, could you try this with a different SSH server, and report the version numbers of the servers you tested with?

**Comment by Nikratio** [comment] 2018-12-22 14:31
I'm closing this bug report for now. Please note that this isn't meant to imply that you haven't found a bug - you most likely have and I'm grateful that you took the time to report it. However, without additional information it is unlikely that anyone is going to be able to do anything but this, and I prefer to use the issue tracker as a tool to manage ongoing work (as opposed to a database of known/potential issues). 

Please feel free to re-open this if you can provide the requested information!

**Closed by Nikratio** 2018-12-22 14:31 UTC
Labels: needs-info

**Comment by markcaudill** [comment] 2018-12-22 16:44
Thanks. Sorry for not responding sooner. I no longer have access to the systems involved so I can't reproduce this. For reference, the target system was Axway SecureTransport (unsure of the version) and the SSHFS client was running on RHEL 7. I suspect the issue was with the SecureTransport implementation but I can't say for sure.
