### ISSUE TITLE
sshfs on macOS mounting when SSH authentication fails

### ISSUE THREAD

**Issue by kmendoza-bt** [libfuse/sshfs#197] opened 2019-11-28 22:49 UTC
When the "ssh" process spawned by sshfs on macOS receives a keyboard interrupt during authentication, the mount is still being done even though there is no connection to the remote side. Attempting to do "ls" on the directory triggers a "Device not configured" error.

Here are the steps that triggers the issue:
1. Run sshfs to attempt to mount a remote directory on a Linux system.
2. At the password prompt hit ctrl+c.
3. Observe that no other messages are displayed.
4. Observe that "mount" entry for the remote directory mounted to the specified mount point.
5. Run "ls" and observe the "Device not configured" message is printed on the console.

Version info:
* macOS 10.15.1
* ssh -V output
  OpenSSH_7.9p1, LibreSSL 2.7.3
* sshfs --version output:
  SSHFS version 2.5 (OSXFUSE SSHFS 2.5.0)
  OSXFUSE 3.10.3
  FUSE library version: 2.9.7

**Comment by Nikratio** [comment] 2019-11-29 09:15
Duplicate of #111

**Closed by Nikratio** 2019-11-29 09:15 UTC
Labels: duplicate

**Comment by bfleischer** [comment] 2024-12-03 09:13
This issue has been addressed in macFUSE 4.6.2. Since 4.6.2 the `FUSE_INIT` handshake is performed synchronously during the `mount(2)` syscall. The mount operation will fail (and the volume will not be mounted as a result) unless SSHFS handles the `FUSE_INIT` handshake.
