### ISSUE TITLE
Different `lstat` results for processes with same permissions

### ISSUE THREAD

**Issue by naktinis** [libfuse/sshfs#222] opened 2020-08-07 14:10 UTC
I have two identical processes that run with identical permissions (let's call them A and B) that access the same SSHFS mount.
- Process A is started, it calls `lstat("/sshfs-mount/file", ...)`, gets a correct result
- Proc. A keeps running for some hours
- Proc. A calls `lstat("/sshfs-mount/file", ...)` again, this time and from now on fails with `EACCES (Permission denied)`
- Meanwhile proc. B (identical to A) is started, calls `lstat("/sshfs-mount/file", ...)`, gets a correct result every time (for at least some hours)

How is it possible that A and B get different responses to the same `lstat` call with the same arguments while having the same permissions? Is this something that SSHFS can control or is this a kernel bug/feature?

Processes A and B are, in fact, mergerfs processes, although not sure if that's relevant. The original issue is documented here and includes straces: https://github.com/trapexit/mergerfs/issues/802

**Comment by Nikratio** [comment] 2020-11-09 09:42
Thanks for the report! Yeah, this shouldn't happen.

Is there a way to reliable reproduce this problem?

**Comment by naktinis** [comment] 2020-11-09 10:28
@trapexit and I have narrowed the issue down to me _not_ using an `allow_other` option on the SSHFS mount. See the last four comments on this issue: https://github.com/trapexit/mergerfs/issues/802#issuecomment-673087746.

This comment describes the SSHFS options I was using: https://github.com/trapexit/mergerfs/issues/802#issuecomment-670204018. If I remember correctly, I was reproducing it by listing files on the mount as different users (sometimes root, sometimes non-root). I hope that helps.

**Comment by Nikratio** [comment] 2020-11-09 10:38
Are you saying that the processes with "identical permissions" are actually running as different users? 

In that case not using `allow_other` should *never* allow the other process to access the mountpoint. Certainly not "after some hours".

Could you please explain the complete setup once more in more detail? Ideally with a script that reproduces the issue?

**Comment by naktinis** [comment] 2020-11-09 10:59
Sorry for not being clear. No, the processes are identical and running as the same user. Rather, two different users are using/reading the mounts (prob. resulting in `setgroups(1, [<UID>])` and `setreuid(-1, <UID>)` being run by the reading process and immediately after that making the files forever inaccessible to that particular process even for root as demonstrated in this strace: https://github.com/trapexit/mergerfs/issues/802#issuecomment-673070618).

Could also potentially be a FUSE or a kernel issue – I don't have a sufficient depth of understanding to claim that it's really an SSHFS bug. Just that changing an SSHFS mount option fixes it.

The setup was as follows:
```
sshfs -o ro,reconnect,cache=no,ServerAliveInterval=5,ServerAliveCountMax=120,ssh_command=ssh -o LogLevel=ERROR -o ConnectTimeout=3 -o ConnectionAttempts=2 [USER]@[REMOTE]:/a /a
```
```
mergerfs -o defaults,ro,allow_other,use_ino,cache.files=off,dropcacheonclose=true,category.search=newest,nosuid,nodev,nonempty /a:/b /ab
```
`/b` just being a regular local directory (Btrfs).
And then the files were being read via mergerfs (`/ab/...`) by two different users (one root, other not).

**Comment by Nikratio** [comment] 2020-11-09 12:34
Could you try to reproduce this issue with out mergerfs in the loop? I.e., create a small test client that issues the same `setgroups()` & `setreuid()` calls and acts directly on the SSHFS mountpoint? 

This would make it much easier to nail down and fix the issue, no matter if it is in libfuse, SSHFS, or the FUSE kernel module.

**Comment by Nikratio** [comment] 2021-06-08 08:14
I'm closing this issue for now. Please note that this isn't meant to imply that you haven't found a real bug or worthwhile potential improvement - you most likely have and I'm grateful that you took the time to report it.

Unfortunately, this project does not currently have any active, regular contributors. As the maintainer, I try to review pull requests and make regular releases, but unfortunately I have no capacity to do significant development beyond that.
Issue reports that do not come with a pull request or clearly have high impact on a large number of users are therefore likely to languish.

I understand that this is frustrating for users, but I hope you can also understand that any development work that I do on this project has to compete with spending time with my family, doing work that I get paid for, doing something recreational without a computer, or working on features/bugs that affect me personally. Most bugs and ideas - unfortunately including this one - loose out in this competition.

In other words, unless you plan to work on this yourself or can recruit someone who will, it's unlikely that anyone is going to do anything about it anytime soon.

Still, you may wonder why I am closing the issue rather than keeping it open.

In short, I want the issue tracker to show the most important issues that users should be aware of and where prospective contributors could make the biggest difference. I do not think there is much value in using it as an exhaustive database of every idea or glitch that someone has ever encountered - especially if no one is intending to address/implement it.

For this reason, I am closing most issues when it becomes clear that they're unlikely to see any activity in the near future - and this seems to be the case here.

I understand that you have invested time and effort in reporting this, and I am very sorry that currently there is no way to build upon this. I wish the situation was different.

**Closed by Nikratio** 2021-06-08 08:14 UTC
Labels: bug, needs-info
