### ISSUE TITLE
Seeking in directory stream has no effect

### ISSUE THREAD

**Issue by rozhuk-im** [libfuse/sshfs#211] opened 2020-05-09 06:43 UTC
Usual usage - works ok:
```
# mkdir ~/mnt/172.16.0.254/tmp/111
mkdir: /home/rim/mnt/172.16.0.254/tmp/111: File exists
Exit 1
rim@rimwks# rm -rf ~/mnt/172.16.0.254/tmp/111
rim@rimwks# mkdir ~/mnt/172.16.0.254/tmp/111
rim@rimwks# rm -rf ~/mnt/172.16.0.254/tmp/111
rim@rimwks# ls ~/mnt/172.16.0.254/tmp/
total 2228
drwxrwxrwt  1 root  wheel   384B May  9 09:30:31 2020 ./
drwxr-xr-x  1 root  wheel   1.0K Nov  3 23:37:03 2018 ../
drwx------  1 root  wheel    64B May  9 08:54:36 2020 mc-root/
srwxrwxrwx  1 88    wheel     0B May  9 06:53:04 2020 mysql.sock=
drwxr-xr-x  1 www   www     256B May  9 06:53:02 2020 nginx/
-rw-r-----  1 242   wheel   284B May  9 06:53:00 2020 prosody.err
-rw-r-----  1 242   wheel   2.2M May  9 09:30:17 2020 prosody.log
drwxrwxrwt  1 root  wheel     0B May  9 09:52:52 2020 vi.recover/
```

Log:

<details>

```
# sshfs -o sshfs_debug root@172.16.0.254:/ /home/rim/mnt/172.16.0.254/
SSHFS version 3.7.0
executing <ssh> <-x> <-a> <-oClearAllForwardings=yes> <-2> <root@172.16.0.254> <-s> <sftp>
Server version: 3
Extension: posix-rename@openssh.com <1>
Extension: statvfs@openssh.com <2>
Extension: fstatvfs@openssh.com <2>
Extension: hardlink@openssh.com <1>
Extension: fsync@openssh.com <1>
Extension: lsetstat@openssh.com <1>
[00001] LSTAT
  [00001]          ATTRS       41bytes (0ms)
[00002] EXTENDED
  [00002] EXTENDED_REPLY       97bytes (0ms)
[00003] OPENDIR
  [00003]         HANDLE       17bytes (0ms)
[00004] READDIR
[00005] READDIR
  [00004]           NAME     2193bytes (1ms)
  [00005]         STATUS       32bytes (1ms)
[00006] READDIR
[00007] READDIR
[00008] READLINK
  [00006]         STATUS       32bytes (0ms)
  [00007]         STATUS       32bytes (0ms)
  [00008]           NAME       47bytes (0ms)
[00009] LSTAT
  [00009]          ATTRS       41bytes (0ms)
[00010] LSTAT
  [00010]          ATTRS       41bytes (0ms)
[00011] EXTENDED
  [00011] EXTENDED_REPLY       97bytes (0ms)
[00012] LSTAT
  [00012]         STATUS       33bytes (0ms)
[00013] EXTENDED
  [00013] EXTENDED_REPLY       97bytes (0ms)
[00014] OPENDIR
  [00014]         HANDLE       17bytes (0ms)
[00015] READDIR
[00016] READDIR
  [00015]           NAME      997bytes (0ms)
  [00016]         STATUS       32bytes (0ms)
[00017] READDIR
[00018] READDIR
  [00017]         STATUS       32bytes (0ms)
  [00018]         STATUS       32bytes (0ms)
[00019] EXTENDED
  [00019] EXTENDED_REPLY       97bytes (0ms)
[00020] EXTENDED
  [00020] EXTENDED_REPLY       97bytes (0ms)
[00021] EXTENDED
  [00021] EXTENDED_REPLY       97bytes (0ms)
[00022] OPENDIR
  [00022]         HANDLE       17bytes (0ms)
[00023] READDIR
[00024] READDIR
  [00023]           NAME      211bytes (0ms)
  [00024]         STATUS       32bytes (0ms)
[00025] READDIR
[00026] READDIR
[00027] CLOSE
  [00025]         STATUS       32bytes (0ms)
  [00026]         STATUS       32bytes (0ms)
  [00027]         STATUS       28bytes (0ms)
[00028] EXTENDED
  [00028] EXTENDED_REPLY       97bytes (0ms)
[00029] EXTENDED
  [00029] EXTENDED_REPLY       97bytes (0ms)
[00030] RMDIR
  [00030]         STATUS       28bytes (0ms)
[00031] LSTAT
  [00031]          ATTRS       41bytes (0ms)
[00032] EXTENDED
  [00032] EXTENDED_REPLY       97bytes (0ms)
[00033] EXTENDED
  [00033] EXTENDED_REPLY       97bytes (0ms)
[00034] EXTENDED
  [00034] EXTENDED_REPLY       97bytes (0ms)
[00035] READDIR
[00036] READDIR
  [00035]         STATUS       32bytes (0ms)
  [00036]         STATUS       32bytes (0ms)
[00037] EXTENDED
  [00037] EXTENDED_REPLY       97bytes (0ms)
[00038] EXTENDED
  [00038] EXTENDED_REPLY       97bytes (0ms)
[00039] EXTENDED
  [00039] EXTENDED_REPLY       97bytes (0ms)
[00040] EXTENDED
  [00040] EXTENDED_REPLY       97bytes (0ms)
[00041] EXTENDED
  [00041] EXTENDED_REPLY       97bytes (0ms)
[00042] CLOSE
[00043] CLOSE
  [00042]         STATUS       28bytes (0ms)
  [00043]         STATUS       28bytes (0ms)

sent:               43 messages, 1064 bytes
received:           43 messages, 5712 bytes
rtt min/max/avg:    0ms/1ms/0ms
num connect:        1
```
</details>

With mc:
cd /home/rim/mnt/172.16.0.254/
cd /home/rim/mnt/172.16.0.254/tmp
rm -rf /home/rim/mnt/172.16.0.254/tmp/111
NO FILES shown in dir, even with ```ls``` on console.

Log:

<details>

```
# sshfs -o sshfs_debug root@172.16.0.254:/ /home/rim/mnt/172.16.0.254/
SSHFS version 3.7.0
executing <ssh> <-x> <-a> <-oClearAllForwardings=yes> <-2> <root@172.16.0.254> <-s> <sftp>
Server version: 3
Extension: posix-rename@openssh.com <1>
Extension: statvfs@openssh.com <2>
Extension: fstatvfs@openssh.com <2>
Extension: hardlink@openssh.com <1>
Extension: fsync@openssh.com <1>
Extension: lsetstat@openssh.com <1>
[00001] LSTAT
  [00001]          ATTRS       41bytes (0ms)
[00002] LSTAT
  [00002]          ATTRS       41bytes (0ms)
[00003] EXTENDED
  [00003] EXTENDED_REPLY       97bytes (0ms)
[00004] OPENDIR
  [00004]         HANDLE       17bytes (0ms)
[00005] READDIR
[00006] READDIR
  [00005]           NAME      997bytes (0ms)
  [00006]         STATUS       32bytes (0ms)
[00007] READDIR
[00008] READDIR
  [00007]         STATUS       32bytes (0ms)
  [00008]         STATUS       32bytes (0ms)
[00009] CLOSE
  [00009]         STATUS       28bytes (0ms)
[00010] EXTENDED
  [00010] EXTENDED_REPLY       97bytes (0ms)
[00011] EXTENDED
  [00011] EXTENDED_REPLY       97bytes (0ms)
[00012] OPENDIR
  [00012]         HANDLE       17bytes (0ms)
[00013] READDIR
[00014] READDIR
  [00013]           NAME      211bytes (0ms)
  [00014]         STATUS       32bytes (0ms)
[00015] READDIR
[00016] READDIR
[00017] CLOSE
[00018] RMDIR
  [00015]         STATUS       32bytes (0ms)
  [00016]         STATUS       32bytes (0ms)
  [00017]         STATUS       28bytes (0ms)
  [00018]         STATUS       28bytes (0ms)
[00019] LSTAT
  [00019]          ATTRS       41bytes (0ms)
[00020] LSTAT
  [00020]         STATUS       33bytes (0ms)
[00021] MKDIR
  [00021]         STATUS       28bytes (0ms)
[00022] LSTAT
  [00022]          ATTRS       41bytes (0ms)
[00023] LSTAT
  [00023]          ATTRS       41bytes (0ms)
[00024] EXTENDED
  [00024] EXTENDED_REPLY       97bytes (0ms)
[00025] EXTENDED
  [00025] EXTENDED_REPLY       97bytes (0ms)
[00026] OPENDIR
  [00026]         HANDLE       17bytes (0ms)
[00027] READDIR
[00028] READDIR
  [00027]           NAME      211bytes (0ms)
  [00028]         STATUS       32bytes (0ms)
[00029] READDIR
[00030] READDIR
[00031] CLOSE
[00032] RMDIR
  [00029]         STATUS       32bytes (0ms)
  [00030]         STATUS       32bytes (0ms)
  [00031]         STATUS       28bytes (0ms)
  [00032]         STATUS       28bytes (0ms)
[00033] LSTAT
  [00033]          ATTRS       41bytes (0ms)
[00034] EXTENDED
  [00034] EXTENDED_REPLY       97bytes (0ms)
[00035] OPENDIR
  [00035]         HANDLE       17bytes (0ms)
[00036] READDIR
[00037] READDIR
  [00036]           NAME      895bytes (0ms)
  [00037]         STATUS       32bytes (0ms)
[00038] READDIR
[00039] READDIR
  [00038]         STATUS       32bytes (0ms)
[00040] CLOSE
  [00039]         STATUS       32bytes (0ms)
  [00040]         STATUS       28bytes (0ms)
```
</details>

I suspect that this happen because mc use file monitor that open all dirs and all files, and then open dir changes - readdir fail to read new data or probably read offset point to wrong position.

Looks like this commit causes this: https://github.com/libfuse/sshfs/commit/493081e8f64c3fedb430704485aebbe32edf8ac1#diff-a0a498b859a2c8d3c48c2ad49582821b

**Comment by rozhuk-im** [comment] 2020-05-09 21:14
Looks like this is not FreeBSD/my personal use issue.
This happen because handle cached after ```opendir()``` but ```readdir()```  does not use ```offset```.

**Comment by rozhuk-im** [comment] 2020-05-14 07:56
IMHO this be can reproduced on every system:
1. mount something via sshfs to /mnt/tmp/
2. mkdir -p /mnt/tmp/dddir
3. open("/mnt/tmp/dddir", RO) in some prog and keep handle open.
4. touch  /mnt/tmp/dddir/fffile1 /mnt/tmp/dddir/fffile2 /mnt/tmp/dddir/fffile3
5. rm -f /mnt/tmp/dddir/fffile1
6. ls /mnt/tmp/dddir/ - should show zero files.

**Comment by Nikratio** [comment] 2020-05-14 19:10
Your step `6` does not need to show zero files. readdir() is free to ignore deletions and creations that happen while the directory stream is open - as long as no entry is returned twice. From https://pubs.opengroup.org/onlinepubs/9699919799/functions/readdir.html:

> If a file is removed from or added to the directory after the most recent call to opendir() or rewinddir(), whether a subsequent call to readdir() returns an entry for that file is unspecified.

That said, there is a bug in the readdir handler. It ought to take a look at the `offset` parameter and check if it matches the offset that was passed to the last successful `fuse_fill_dir` call. If it does not match, it should return an error to indicate that seeking in an open stream is not supported.

**Comment by rozhuk-im** [comment] 2020-05-15 04:17
There is no way to implement ```offset``` in sshfs for ```readdir()```.
You can see in code ```assert(offset==0)``` from authors, not mine.

**Comment by Nikratio** [comment] 2020-05-15 18:33
I do see the code, and as I said, I do see that it is buggy. This is certainly not your fault, but it certainly can be fixed. I've already outlined one approach above (confirm that the client is not seeking, and return an error if it does). Another approach would be to always retrieve the full list from the SFTP server and buffer it in memory.

**Comment by Nikratio** [comment] 2022-03-27 11:07
Marking as duplicate of #278

**Closed by Nikratio** 2022-03-27 11:07 UTC
Labels: bug
