### ISSUE TITLE
Install mount.sshfs symlink

### ISSUE THREAD

**Issue by anatol** [libfuse/sshfs#92] opened 2017-09-10 02:28 UTC
Here is a follow-up for Arch discussions

https://bugs.archlinux.org/task/55564
https://bbs.archlinux.org/viewtopic.php?id=229656

Fuse 3.0 release documentation states there should be two separate mount binaries: `mount.fuse` and `mount.fuse3`. As such any fuse filesystem that is linked against fuse3 package (like current Arch sshfs) should be mounted in `/etc/fstab` with filesystem type `fuse3.sshfs`. This in turn requires changes to user configs. Is it something sshfs/fuse developers did intentionally? Is there any chance to have just one `mount.fuse` binary?

If you suggest `fuse3.sshfs` then it seems has another problem:
```
$ mount /media
/bin/sh: fuse3.sshfs: command not found
```

**Comment by Nikratio** [comment] 2017-09-11 08:02
The issue is that fuse 2.x and fuse 3.x are fundamentally incompatible, and that file systems designed for fuse 2.x are expected to stay around for a long time. So the only way to use fuse 2.x and 3.x file systems at the same time is for fuse 3.x to use new names for the binaries.

Symlinking `mount.fuse` to `mount.fuse3` is a bad idea and will lead to trouble sooner or later.

If SSHFS is designed for libfuse3 but installs as `fuse.sshfs`, that's a bug in SSHFS. But I believe SSHFS installs simply as `sshfs`. Is maybe something in Arch creating a symlink from `fuse.sshfs`?

Unfortunately I do not see a way to avoid changing entries in `fstab`.

**Comment by majewsky** [comment] 2017-09-11 09:52
> Unfortunately I do not see a way to avoid changing entries in fstab.

How? As said above, a filesystem type of `fuse3.sshfs` in fstab does not work.

**Comment by Nikratio** [comment] 2017-09-11 09:53
I believe with a standard sshfs installation, a `fuse.sshfs` entry never worked either. There's some magic in the Arch packaging that made it work, and that magic need to be adjusted.

**Comment by anatol** [comment] 2017-09-12 14:48
@Nikratio would it be possible to make `mount.fuse` handle both fuse2 and fuse3? The fact whether filesystem linked with library v2 or v3 is really an implementation detail and should not be dumped on users. Having a single filesystem name would simplify the migration.

**Comment by Nikratio** [comment] 2017-09-12 18:56
I've never worked with this part of the code before, but looking at `mount.fuse.c` it seems that this is really just a wrapper that, when called for `fuse.foo` attempts to exec `foo` instead. So it should be possible to extend this to work with `fuse3.foo`. But there is a problem: how do we guarantee that `mount.fuse` exists? If we ship it with libfuse2 and libfuse3, they conflict again. If we ship it in only one version, it may be missing on systems that only have the other version.

**Comment by Nikratio** [comment] 2017-09-12 18:57
An alternative solution (that would have to be implemented for every filesystem though) is for SSHFS simply to install not just the `sshfs` binary, but also a symlink from `mount.fuse.sshfs`.

**Comment by Nikratio** [comment] 2017-09-12 18:59
Actually, I think the cleanest solution in the long-term is for SSHFS to install a `mount.sshfs` symlink and require users to put `sshfs` instead of `fuse.sshfs` into `/etc/fstab`. That way, there's no dependency on the FUSE version.

**Comment by anatol** [comment] 2017-09-12 19:29
> it seems that this is really just a wrapper

Yes, and that is why I think it should be shared and user config changes should be avoided.

> If we ship it with libfuse2 and libfuse3, they conflict again.

fuse2 and v3 already ship conflicting files. https://github.com/libfuse/libfuse/releases/tag/fuse-3.0.0 states:
```
However, some files will be installed by both libfuse 2 and libfuse 3 (e.g. /etc/fuse.conf, the udev and init scripts, and the
mount.fuse(8) manpage).
```

It makes sense to include `fuse.mount` to the list as well.

Arch Linux resolves the conflict by having [fuse-common package](https://www.archlinux.org/packages/extra/x86_64/fuse-common/) with common files. Other distros have similar solution. If you confirm that `fuse.mount` is going to be shared between the versions then I'll make Arch Linux changes and it will fix the original issue.

**Comment by anatol** [comment] 2017-09-12 19:37
And the same question applies to `fusermount` binary. The binary does not use libfuse shared library. In this case does the binary need to be duplicated in fuse2 and fuse3?

**Comment by Nikratio** [comment] 2017-09-12 19:56
The interface between the shared object and fusermount will change (actually, it might have already - not sure what I committed when), so there needs to be one fusermount per so version.

**Comment by anatol** [comment] 2017-09-12 20:41
> The interface between the shared object and fusermount

What kind of changes is it? Is it possible for `fusermount` to detect the fuse version and handle differences internally? Having only one `fusermount` version that works the same way for all fuse filesystems would definitely improve user experience.

**Comment by anatol** [comment] 2017-09-12 20:42
Also note that `fusermount/fusermount3` does not link with libfuse shared library:
```
$ ldd /usr/bin/fusermount3
	linux-vdso.so.1 (0x00007ffe86cfe000)
	libc.so.6 => /usr/lib/libc.so.6 (0x00007fa6dd144000)
	/lib64/ld-linux-x86-64.so.2 => /usr/lib64/ld-linux-x86-64.so.2 (0x00007fa6dd703000)
```

**Comment by Nikratio** [comment] 2017-09-12 21:59
Almost anything is possible if someone does the work :-). For me, having fusermount be cross-version compatible is very low on the priority list. Yes, fusermount does not link against libfuse.so.

**Comment by Nikratio** [comment] 2017-09-12 22:00
See https://github.com/libfuse/libfuse/issues/77 for an example of the changes in the libfuse.so / fusermount interface.

**Comment by anatol** [comment] 2017-09-13 20:44
Thanks for details.

What about `mount.fuse` binary? Could it be shared between different fuse versions? If yes it would simplify user's life.

**Comment by Nikratio** [comment] 2017-09-14 09:43
Technically it would be easy enough since it's just a wrapper. Not sure if I like the idea of two packaging installing the same binary though. Configuration files are different.

**Comment by majewsky** [comment] 2017-09-14 09:45
What about doing the same thing that Arch is already doing in their packaging, and putting the common parts in a fuse-common repository with a separate release tarball? It's probably too late to make this a dependency of Fuse 2, but it could be a dependency of Fuse 3 and all later versions.

**Comment by Nikratio** [comment] 2017-09-14 10:34
Could be done, but I am not sure if the extra work is worth the gain.

**Closed** 2017-09-20 13:28 UTC
Labels: enhancement
